In [1]:
import pandas as pd
data=pd.read_csv('kr_googlestore.csv')

# 4. Missing data

### a. data.dropna(how='any')
### b. data.fillna(value= __ )
### c. pd.isna(data)
(10minutes to pandas)에서 다룬것 

(추가)
### d. pd.isnull(data), .notnull()
### e. data.isnull().sum()


----

결측값을 의미하는 여러 데이터형

#### Na : Not available, 결측값
#### Null : 값이 없다.
#### NaN : Not a Number, 수학적으로 정의되지 않는다.


* 0은 결측값이 아니라 0이라는 값이다

---

### Pandas는 결측치를 np.nan로 대표적으로 표현하고 기본적으로 컴퓨테이션 계산에 포함하지 않는다.

### Reindexing은 특정 열의 인덱스를 바꾸거나 더하거나 삭제하는 것을 하게 하는 메서드.
복사값을 return한다.

#### 데이터에 ios버전 유무 컬럼을 넣어보자

In [2]:
data1 = data.reindex(index=range(5, 15), columns=list(data.columns) +['ios_ver'])

그 중 2개만 True값을 넣는다면, 나머지는 NaN값이 뜬다.

In [3]:
data1.loc[0:5:2, 'ios_ver'] = True

In [4]:
data1

,어플,장르,등급,리뷰 수,크기,설치 수,타입,가격,연령층,안드로이드 버전,업데이트_년도,업데이트_달,업데이트_년달,ios_ver
5,Paper flowers instructions,Art & Design,4.4,167,5.6,50000,무료,0,전체가,2.3,2017,3,2017.03,True
6,Smoke Effect Photo Maker - Smoke Editor,Art & Design,3.8,178,190.0,50000,무료,0,전체가,4.0,2018,4,2018.04,NaN
7,Infinite Painter,Art & Design,4.1,36815,290.0,1000000,유료,$4.99,전체가,4.2,2018,6,2018.06,NaN
8,Garden Coloring Book,Art & Design,NaN,13791,330.0,1000000,무료,0,전체가,3.0,2017,9,2017.09,NaN
9,Kids Paint Free - Drawing Fun,Art & Design;Creativity,4.7,121,3.1,10000,무료,0,전체가,4.0,2018,7,2018.07,NaN
10,Text on Photo - Fonteee,Art & Design,4.4,13880,280.0,1000000,무료,0,전체가,4.1,2017,10,2017.10,NaN
11,Name Art Photo Editor - Focus n Filters,Art & Design,4.4,8788,120.0,1000000,무료,0,전체가,4.0,2018,7,2018.07,NaN
12,Tattoo Name On My Photo Editor,Art & Design,NaN,44829,200.0,10000000,무료,0,청소년,4.1,2018,4,2018.04,NaN
13,Mandala Coloring Book,Art & Design,4.6,4326,210.0,100000,무료,0,전체가,4.4,2018,6,2018.06,NaN
14,3D Color Pixel by Number - Sandbox Art Coloring,Art & Design,NaN,1518,370.0,100000,유료,$1.99,전체가,2.3,2018,8,2018.08,NaN

### a. 결측값이 어디라도 있는 데이터를 삭제해보자

In [5]:
data1.dropna(how='any')

,어플,장르,등급,리뷰 수,크기,설치 수,타입,가격,연령층,안드로이드 버전,업데이트_년도,업데이트_달,업데이트_년달,ios_ver
5,Paper flowers instructions,Art & Design,4.4,167,5.6,50000,무료,0,전체가,2.3,2017,3,2017.03,True

### b. data.fillna( value = n )

등급 결측치를 삭제하지 말고, 등급의 평균으로 채워보자

데이터 전체를 선택해서 채울수도, 컬럼만 선택해서 채울 수도 있다.

In [6]:
data['등급'].mean().round(1) #round(n)는 소수n자리 수까지 반올림 해준다.

4.3

In [7]:
data['등급'].fillna(value = data['등급'].mean().round(1))

0     4.1
1     3.9
2     4.7
3     4.5
4     4.3
     ...
95    4.0
96    4.3
97    4.0
98    4.7
99    4.3
Name: 등급, Length: 100, dtype: float64

### c. pd.isna(data)

값이 nan인지를 불린boolean으로 보고 싶다면 아래 메서드를 쓰면 된다.

그런데 체크해 보니 fillna로는 데이터가 바뀌지 않았다. copy를 해서 값을 넣어주기 때문!

In [8]:
pd.isna(data)

,어플,장르,등급,리뷰 수,크기,설치 수,타입,가격,연령층,안드로이드 버전,업데이트_년도,업데이트_달,업데이트_년달
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,True,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,True,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,True,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,True,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,False,False,False,False,False,False,False,False,False,False,False,False,False
71,False,False,True,False,False,False,False,False,False,False,False,False,False
72,False,False,False,False,False,False,False,False,False,False,False,False,False
73,False,False,False,False,True,False,False,False,False,False,False,False,False
74,False,False,False,False,False,False,False,False,False,False,False,False,False
75,False,False,False,False,False,False,False,False,False,False,False,False,False
76,False,False,False,False,False,False,False,False,False,False,False,False,False
77,False,False,False,False,False,False,False,False,False,False,False,False,False
78,False,False,True,False,False,False,False,False,False,False,False,False,False
79,False,False,False,False,False,False,False,False,False,False,False,False,False
80,False,False,False,False,False,False,False,False,False,False,False,False,False
81,False,False,False,False,False,False,False,False,False,False,False,False,False
82,False,False,False,False,False,False,False,False,False,False,False,False,False
83,False,False,False,False,False,False,False,False,False,False,False,False,False
84,False,False,False,False,False,False,False,False,False,False,False,False,False
85,False,False,True,False,True,False,False,False,False,False,False,False,False
86,False,False,False,False,False,False,False,False,False,False,False,False,False
87,False,False,False,False,False,False,False,False,False,False,False,False,False
88,False,False,False,False,True,False,False,False,False,False,False,False,False
89,False,False,False,False,True,False,False,False,False,False,False,False,False
90,False,False,False,False,False,False,False,False,False,False,False,False,False
91,False,False,False,False,False,False,False,False,False,False,False,False,False
92,False,False,True,False,True,False,False,False,False,False,False,False,False
93,False,False,False,False,False,False,False,False,False,False,False,False,False
94,False,False,False,False,False,False,False,False,False,False,False,False,False
95,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,True,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,True,False,False,False,False,False,False,False,False,False,False

#### 그래서 원본을 수정하고 싶다면 아래처럼 덮어 씌워주면 된다.

In [9]:
data = data['등급'].fillna(value = data['등급'].mean().round(1))

In [10]:
pd.isna(data)

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: 등급, Length: 100, dtype: bool

---


# 왜 데이터에 결측값이 있으면 안좋을까요? 
### 어떤 상황에 어떤 값으로 채워 넣는 것이 데이터를 최대한 훼손하지 않는 방법일까요?

10명의 사람들의 키 평균을 재려고 하는데, 세 사람이 키를 적어내지 않았다. 이 사람들이 평균에 포함이 될 수 있을까?


판다스 내부 함수들에서 이런 경우들을 자동으로 처리해주는 메서드가 많긴 하지만, 데이터끼리 합치거나 계산하게 될 때 에러가 생기는 경우가 많다.



### a. 내 데이터에 missing 값이 있는지 체크해 보기
- isnull() 메소드는 관측치가 결측이면, True / 결측이 아니면, False의 boollean 값 반환
- notnull()메소드는 관측치가 결측이면, False / 결측이 아니면, True의 boollean 값 반환 -> isnull 정반대.

In [11]:
pd.isnull(data)

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: 등급, Length: 100, dtype: bool

### b. 칼럼별 결측값 개수 구하기: df.isnull().sum()


boolean 타입은 0(False)과 1(True)로 값이 변환이 되기 때문에 sum()을 할 경우, True의 경우들의 갯수가 나옵니다.

In [12]:
data.isnull().sum()

0

<br>

특정 칼럼 '크기'에 결측값이 몇개 있는지 알고 싶을 때는 컬럼명으로 인덱싱을 해준 후 isnull().sum()을 해주면 됩니다.

In [ ]:
data['크기'].isnull().sum()

<br>

### c. **결측치 연산 방법**
- 참고: https://rfriend.tistory.com/261?category=675917

1) sum(), cumsum() methods 계산 시 : NaN은 '0'으로 처리

2) mean(), std() 연산 시 : NaN은 분석 대상(population)에서 제외

3) DataFrame 칼럼 간 연산 시 : NaN이 하나라도 있으면 NaN 반환
4) 컬럼을 아예 삭제하거나 등등등등

In [ ]:
# Nan 제외하고 평균 만들어짐.
data['등급'].mean()

In [ ]:
# Nan 제외하고 std 만들어짐.
data['등급'].std()

In [ ]:
data['크기'].mean()

In [ ]:
# 데이터 null 값 넣기. 
data.loc[data['등급'].isnull(), '등급'] = 4.2
data.loc[data['크기'].isnull(), '크기'] = 144.2
# data=data.fillna(data.mean())

In [ ]:
data.isnull().sum()

In [ ]:
# 조건을 충족할 때, 결측치를 넣어주세요. 
'''
check_null = data['등급'].isnull()
condition1 = data['리뷰수'] >= 100

data.loc[check_null & condition1, '등급'] = 4.2 '''

**타입에 일부러 nan만들어서, 조건 충족 하면 어떨까요?**

In [ ]:
# data.loc[data['등급'].isnull(), '등급'] = 4.2

In [ ]:
# .T 속성 -> Transpose index and columns. => index와 column 바꾼 형태.
# data.T

In [ ]:
# 각 인덱스에 대한 이름 설정하기
data.index.name = '순서'
data